sudo: required

language: php

php:
  - 7.2

services:
  - docker
  - docker-compose

before_install:
  - docker-compose migrate-to-labels
  - sudo chmod 777 config.sh
  - sudo ./config.sh

script:
  - docker exec -it ingresse-php-fpm vendor/bin/phpunit